[deps]
ABCDGraphGenerator = "4c9194b5-d5d9-4bea-bd96-43ca8ce89b0b"
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CGE = "f7ff1d1e-e254-4b26-babe-fc3421add060"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Dagger = "d58978e5-989f-55fb-8d15-ea34adc7bf54"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FreqTables = "da1fdf0e-e0ff-5433-a45f-9bb5ff651cb1"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultiJuMP = "f6097e2c-3ba3-5605-a9a8-3a277acb490f"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
OSMToolset = "a1c25ae6-0f93-4b3a-bddf-c248cb99b9fa"
OpenStreetMapX = "86cd37e6-c0ff-550b-95fe-21d72c8d4fc9"
ParallelDataTransfer = "2dcacdae-9679-587a-88bb-8b444fb7085b"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Parquet2 = "98572fba-bba0-415d-956f-fa77e587d26d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialMatrices = "928aab9d-ef52-54ac-8ca1-acd7ca42c160"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
UMAP = "c4f8c510-2410-5be4-91d7-4fbaeb39457e"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"
